### ISSUE TITLE
Create and implement UI

### ISSUE THREAD

**Issue by quinnha** [LowerEarthOrbiters/Lower_Earth_Orbiters#121]
Design can be found here: https://www.figma.com/file/i2Q2VBK5So9Fr4Y0fTfo8U/MCT-Design?type=design&node-id=0%3A1&mode=design&t=luirTXz6ZzzY3WR5-1

**Comment by quinnha** [comment]
@dhruvcheemakurti @RishiVaya @Umang-Rajkarnikar @DiamondAhuja please have a look at the design and suggest changes if needed! need to bring forth to mist people for preliminary feedback

**Comment by Umang-Rajkarnikar** [comment]
Looks great! Just had a question about the command and logs table, each row would be clickable to show more detail about the command/log right?

**Comment by Umang-Rajkarnikar** [comment]
Oh also could we have a filter where an operator can see their own logs/commands in the two tables?

**Comment by quinnha** [comment]
> Looks great! Just had a question about the command and logs table, each row would be clickable to show more detail about the command/log right?

sure we can do that, this is just a low level prototype



> Oh also could we have a filter where an operator can see their own logs/commands in the two tables? It could be something simple like a dropdown, and the two options are "Yours" and "All"

im guessing it would be per schedule then? i.e the operator wouldnt be able to query logs across all schedules

**Comment by dhruvcheemakurti** [comment]
the design looks great!
