### ISSUE TITLE
REQ-MCT-001 - Service Type

### ISSUE THREAD

**Issue by quinnha** [LowerEarthOrbiters/Lower_Earth_Orbiters#41]
The MCT shall be a web service hosted on a Linux-based server, consisting of a graphical user interface accessible through a web browser (“web interface”) and a TCP port to communicate commands with satellite systems (“command port”).

Steps
- Mock the server
- Connect to NEUDOSE Ground Station server when available

**Comment by quinnha** [comment]
@DiamondAhuja please add updates here including meeting with Austin, and add Dhruv when he gets in the github

**Comment by DiamondAhuja** [comment]
Updates provided by Austin (Stakeholder): 
![image](https://github.com/RishiVaya/Lower_Earth_Orbiters/assets/129548993/fe1efaad-03d8-4c9e-b159-cdc165c3b74d)

Since connecting to the MIST server is a difficult process, SSH tunneling to an external server is being used

**Comment by DiamondAhuja** [comment]
The application is able to successfully run locally as of now on the MIST server.

To mimic the Ground Station, another Ubuntu based VM is implemented which will be used for communicating between the web application and the satellite.

**Comment by quinnha** [comment]
@DiamondAhuja please update
