### ISSUE TITLE
REQ-MCT-007 - Target Identification

### ISSUE THREAD

**Issue by quinnha** [LowerEarthOrbiters/Lower_Earth_Orbiters#47]
The MCT shall accept a target identification message from a client on the command port and associate all subsequent traffic on this connection to the target identified.

**Comment by quinnha** [comment]
@RishiVaya not sure what this is asking, need to clarify with austin.

feel free to add dhruv to this

**Comment by DiamondAhuja** [comment]
@RishiVaya do we have any updates on what we actually have to do in this?

**Comment by RishiVaya** [comment]
@DiamondAhuja I dont think so. It looked a bit related to the stuff u are working on
